# Generated by Django 4.2.29 on 2026-03-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_steps', models.IntegerField(default=0)),
                ('distance_meters', models.FloatField(default=0.0)),
                ('avg_speed_kmh', models.FloatField(default=0.0)),
                ('avg_heart_rate', models.IntegerField(default=0)),
                ('calories_burned', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('activity_type', models.CharField(choices=[('STILL', 'Still'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('squat_count', models.IntegerField(default=0)),
                ('pushup_count', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('squat', 'Squat'), ('pushup', 'Push-up')], max_length=10)),
                ('rep_number', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reps', to='tracker.workoutsession')),
            ],
        ),
    ]
