# Generated by Django 4.2.11 on 2026-03-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditem',
            name='required_level',
            field=models.CharField(default='Tortoise', max_length=50),
        ),
    ]
